# Generated by Django 3.1.3 on 2020-11-26 23:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nivelFormacion', '0002_auto_20201126_2218'),
    ]

    operations = [
        migrations.CreateModel(
            name='Programas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_programa', models.IntegerField()),
                ('nombre_programa', models.CharField(max_length=100)),
                ('cod_formacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nivelFormacion.nivelformacion')),
            ],
        ),
    ]
