# Generated by Django 3.1.3 on 2020-11-26 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nivelFormacion', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nivelformacion',
            old_name='Otros',
            new_name='nombre_formacion',
        ),
    ]
